### PR TITLE
added annote_emg function

### PR DESCRIPTION
**Pull request by HermineBerberyan**

### CODE REVIEW

**Review by smathot — CHANGES_REQUESTED** [review]
This looks good, but it also needs to be incorporate in `_parsing.read_subject()` in the same way that the other preprocessing functions are included.

**Comment by HermineBerberyan** [comment]
> This looks good, but it also needs to be incorporate in `_parsing.read_subject()` in the same way that the other preprocessing functions are included.

Yes, indeed I am working on it

**Comment by smathot** [comment]
You have made these changes in a branch that is behind the `master` branch, resulting in merge conflicts. I'm closing this so you can open a new PR from an up-to-date branch.

**Comment by smathot** [comment]
Don't worry about this one anymore. I resolved the conflict, fixed it, and merged it.

**Pull request closed without merging**
